/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/sheikh-arman/crd-controller/pkg/apis/arman.com/v1alpha1"
	armancomv1alpha1 "github.com/sheikh-arman/crd-controller/pkg/client/applyconfiguration/arman.com/v1alpha1"
	scheme "github.com/sheikh-arman/crd-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ArmansGetter has a method to return a ArmanInterface.
// A group's client should implement this interface.
type ArmansGetter interface {
	Armans(namespace string) ArmanInterface
}

// ArmanInterface has methods to work with Arman resources.
type ArmanInterface interface {
	Create(ctx context.Context, arman *v1alpha1.Arman, opts v1.CreateOptions) (*v1alpha1.Arman, error)
	Update(ctx context.Context, arman *v1alpha1.Arman, opts v1.UpdateOptions) (*v1alpha1.Arman, error)
	UpdateStatus(ctx context.Context, arman *v1alpha1.Arman, opts v1.UpdateOptions) (*v1alpha1.Arman, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Arman, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ArmanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Arman, err error)
	Apply(ctx context.Context, arman *armancomv1alpha1.ArmanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Arman, err error)
	ApplyStatus(ctx context.Context, arman *armancomv1alpha1.ArmanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Arman, err error)
	ArmanExpansion
}

// armans implements ArmanInterface
type armans struct {
	client rest.Interface
	ns     string
}

// newArmans returns a Armans
func newArmans(c *ArmanV1alpha1Client, namespace string) *armans {
	return &armans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the arman, and returns the corresponding arman object, and an error if there is any.
func (c *armans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Arman, err error) {
	result = &v1alpha1.Arman{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("armans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Armans that match those selectors.
func (c *armans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ArmanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ArmanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("armans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested armans.
func (c *armans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("armans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a arman and creates it.  Returns the server's representation of the arman, and an error, if there is any.
func (c *armans) Create(ctx context.Context, arman *v1alpha1.Arman, opts v1.CreateOptions) (result *v1alpha1.Arman, err error) {
	result = &v1alpha1.Arman{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("armans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(arman).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a arman and updates it. Returns the server's representation of the arman, and an error, if there is any.
func (c *armans) Update(ctx context.Context, arman *v1alpha1.Arman, opts v1.UpdateOptions) (result *v1alpha1.Arman, err error) {
	result = &v1alpha1.Arman{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("armans").
		Name(arman.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(arman).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *armans) UpdateStatus(ctx context.Context, arman *v1alpha1.Arman, opts v1.UpdateOptions) (result *v1alpha1.Arman, err error) {
	result = &v1alpha1.Arman{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("armans").
		Name(arman.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(arman).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the arman and deletes it. Returns an error if one occurs.
func (c *armans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("armans").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *armans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("armans").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched arman.
func (c *armans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Arman, err error) {
	result = &v1alpha1.Arman{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("armans").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied arman.
func (c *armans) Apply(ctx context.Context, arman *armancomv1alpha1.ArmanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Arman, err error) {
	if arman == nil {
		return nil, fmt.Errorf("arman provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(arman)
	if err != nil {
		return nil, err
	}
	name := arman.Name
	if name == nil {
		return nil, fmt.Errorf("arman.Name must be provided to Apply")
	}
	result = &v1alpha1.Arman{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("armans").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *armans) ApplyStatus(ctx context.Context, arman *armancomv1alpha1.ArmanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Arman, err error) {
	if arman == nil {
		return nil, fmt.Errorf("arman provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(arman)
	if err != nil {
		return nil, err
	}

	name := arman.Name
	if name == nil {
		return nil, fmt.Errorf("arman.Name must be provided to Apply")
	}

	result = &v1alpha1.Arman{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("armans").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
